export GIT_PAGER=cat

# Inicia tmux automaticamente se não estiver dentro dele
if command -v tmux >/dev/null && [ -z "$TMUX" ]; then
    exec tmux new-session -A -s main
fi

# Carrega Termiris
[ -f ~/.termiris/init.sh ] && . ~/.termiris/init.sh

export PATH="$HOME/.termiris/bin:$PATH"
eval "$(zoxide init bash)"

# fzf
[ -n "$BASH_VERSION" ] && eval "$(fzf --bash)"

[ -f ~/.config/termiris/env ] && . ~/.config/termiris/env

# Termiris history
export HISTFILE="$HOME/.bash_history"
export HISTSIZE=100000
export HISTFILESIZE=200000
export HISTCONTROL=ignoredups:erasedups
export HISTIGNORE="ls:cd:pwd:exit:clear"
shopt -s histappend



# Termiris clean history search
_fzf_termiris_history() {
    local cmd

    history-clean >/dev/null

    cmd=$(tac ~/.termiris/cache/bash_history.clean | fzf) || return

    READLINE_LINE="$cmd"
    READLINE_POINT=${#READLINE_LINE}
}

bind -x '"\C-r":_fzf_termiris_history'
