extra-keys = [ \
  ["ESC","/","-","HOME","UP","END","PGUP"], \
  ["TAB","CTRL","ALT","BACKSLASH","LEFT","DOWN","RIGHT","PGDN"], \
  [{macro:"ALT c",display:"➕"},{macro:"ALT n",display:"▶"},{macro:"kill_window\n",display:"✕"},{macro:"ALT v",display:"📥"},{macro:"ALT y",display:"📋"},{macro:"ALT b",display:"🔍"},{macro:"F1",display:"🤖"},{macro:"CTRL r",display:"🔎"}] \
]
terminal-renderer = software
enforce-char-based-input = true
disable-hardware-acceleration = true
ctrl-space-workaround = true
set-refresh-rate = 60
