extra-keys = [ \
  ["ESC","/","-","HOME","UP","END","PGUP"], \
  ["TAB","CTRL","ALT","BACKSLASH","LEFT","DOWN","RIGHT","PGDN"], \
  [{macro:"ALT c",display:"➕"},{macro:"ALT n",display:"▶"},{macro:"ALT p",display:"◀"},{macro:"kill_window\n",display:"✕"},{macro:"ALT v",display:"📥"},{macro:"ALT y",display:"📋"}] \
]

