set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
set -g history-limit 100000
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
bind r source-file ~/.termiris/config/tmux.conf \; display-message "tmux.conf recarregado"
set -sg escape-time 0
bind -n M-c new-window
bind -n M-n next-window
bind -n M-x kill-window
bind -n M-v run-shell "~/.termiris/bin/colar"
bind -n M-y run-shell "~/.termiris/bin/copiar"
bind -n M-f display-popup -w 100% -h 100% -E "~/.termiris/bin/ff"
bind -n M-b display-popup -w 100% -h 100% -E "~/.termiris/bin/buscar"

bind -n F1 run-shell "~/.termiris/bin/ai"
